name: Daily Discord Post

on:
  schedule:
    - cron: "0 5 * * *"
  workflow_dispatch:

jobs:
  post:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Send image to Discord
        env:
          WEBHOOK_URL: ${{ secrets.DISCORD_WEBHOOK_URL }}
        run: |
          curl -F "file1=@babka.jpeg" "$WEBHOOK_URL"
